### ISSUE TITLE
Feature 1: User can explore all photos of community

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can explore all photos of community

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Upon opening app, the explore page shows photos of all users.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-30 at 11 09 28 AM](https://user-images.githubusercontent.com/113560956/210104564-28272733-c2ee-421e-9f24-4aac8d38c34b.png)

![Screen Shot 2022-12-30 at 11 09 10 AM](https://user-images.githubusercontent.com/113560956/210104570-2636c998-1ed1-4d55-a830-c523835344d2.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] create 4 example users
- [x] add 5 images per user (20 images total)

### ☁️ Server Tasks

- [x] Update `server/index.js` to GET images from all users
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] link bootstrap to HTML
- [x] link styles.css to HTML

### ⚡ Client Tasks

- [x] Create a `navbar` component
- [x] Create a `dropdown menu` component for mobile view
- [x] Create a Explore page to show all images of all users

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
