### ISSUE TITLE
Feature 2: User can select a photo and view full screen

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select a photo and view full screen

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can select a photo and view full screen

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-30 at 11 13 48 AM](https://user-images.githubusercontent.com/113560956/210104794-982c0498-759a-4a60-9b1f-25977eb5c68b.png)
![Screen Shot 2022-12-30 at 11 13 57 AM](https://user-images.githubusercontent.com/113560956/210104799-741d152d-ec3a-4da1-806d-11fb77da61ef.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to include hashed passwords

### ⚡ Client Tasks

- [x] Create a component to for image modal
- [x] Add image handler function to open modal
- [x] Add image handler function to close modal
- [x] Need to target image with event listener

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
