### ISSUE TITLE
Feature 3: User can view list of animal profiles of community

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view list of animal profiles of community

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Clicking on Users link, shows a list of all users of community.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-30 at 11 16 06 AM](https://user-images.githubusercontent.com/113560956/210104964-e01e77b0-93dc-4f73-be1c-83f2c4bd3f27.png)
![Screen Shot 2022-12-30 at 11 15 57 AM](https://user-images.githubusercontent.com/113560956/210104992-111e641c-5ab4-4158-ab5b-574050047e00.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to GET users
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a page component for Users tab
- [x] Create component to fetch all users and display on Users tab

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
