### ISSUE TITLE
Feature 4: User can view photos of a selected animal profile 

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view photos of a selected animal profile

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Clicking on a profile switches to that animal’s profile with only its pictures

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-12-30 at 11 18 12 AM](https://user-images.githubusercontent.com/113560956/210105143-44bdddab-213a-469e-ae6f-23f9ffeacb38.png)
![Screen Shot 2022-12-30 at 11 18 25 AM](https://user-images.githubusercontent.com/113560956/210105145-19148b78-34cc-445b-afa7-58c44c7fa301.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to GET data based on specific userId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to fetch specific userId data
- [x] Create page to display specific user data including header image
- [x] create route path for each user

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
